version: '2'

services:
  app:
    container_name: simple_calc
    build:
      context: ./
      dockerfile: Dockerfile.app
    volumes:
      - ./storage:/var/www/storage
    env_file: '.env'
  web:
    container_name: nginx_server
    build:
      context: ./
      dockerfile: Dockerfile.web
    volumes:
      - ./storage/logs/:/var/log/nginx
    ports:
      - 80:80
